ScanAll method at FullPrimaryKey, HashPrimaryKey
serverless-seoul/dynamorm pull request #11
Opened 2020-07-08 03:40 UTC by extJo

## BACKEND-STORY_ID One-sentence summary of changes

#### Is it a breaking change?: NO

### Why did you make these changes?

When scan all records, for iteration, code is so dirty.
So, i think scanAll support at ORM layer.

### What's changed in these changes?

I added `scanAll` method to `FullPrimaryKey` class.
I added `scanAll` method to `HashPrimaryKey` class.

### What do you especially want to get reviewed?

Is parameter of scanAll method, 'limit' needed?.

### Is there any other comments that every teammate should know?

nope.

### Submission Type

* [ ] Bugfix
* [x] New Feature
* [ ] Refactor

### All Submissions

* [x] Have you added an explanation of what your changes?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you checked potential side effects that could make bad impacts to other services?

### New Features

* [x] Have you configured CI/CD properly?
* [x] Have you configured optimal memory size and timeouts of Lambda Function?
* [ ] Have you grant required permissions (e.g. IAM Policy, VPC Security Group)?
* [ ] Have you made required resources (e.g. DynamoDB Table, RDS Cluster)?
* [ ] Does it requires native addons dependency?

2020-07-08 07:21 UTC, breath103 requested changes

2020-07-08 07:21 UTC, breath103 commented on src/query/hash_primary_key.ts
> +  async scanAll(options: {
요거 query 밑에넣고 GSI / LSI에도 붙여주시면 될듯

2020-07-08 07:21 UTC, breath103 commented on src/query/hash_primary_key.ts
> +    limit?: number;
limit이라는게 그러니까 로딩할 아이템 갯수가 아니고 한번에 로딩하는 아이템 갯수군요.
scanBatchSize? 위에 scan / query 등에서는 limit이라고 하면 읽어올 상품 갯수라서 헷갈릴듯

2020-07-08 07:21 UTC, breath103 commented on src/query/hash_primary_key.ts
> +          .map((i) => scanners[i](lastEvaluatedKeys[i])),
만약 parallelize 햇는데 특정 batch가 로딩이 먼저 끝나면 어떻게 되나요?
레코드가 4개인데 limt=1 3개로 병렬화하면 2개는 한번에 끝나고 1개는 2번 로딩할텐데

2020-07-08 07:34 UTC, extJo commented on src/query/hash_primary_key.ts
> +    limit?: number;
windowSize라고 맨처음에는 했는데 좀 애매하네요

2020-07-08 07:36 UTC, extJo commented on src/query/hash_primary_key.ts
> +  async scanAll(options: {
GSI / LSI의 query 밑에 넣으라는 말씀이시죠?

2020-07-09 05:20 UTC, extJo commented on src/query/hash_primary_key.ts
> +          .map((i) => scanners[i](lastEvaluatedKeys[i])),
특정 segment가 먼저 끝나도 record를 empty로 반환해서 음... 최적화를 더 하려면 할 순 있을꺼같은데

2020-07-09 05:21 UTC, extJo commented on src/query/hash_primary_key.ts
> +          .map((i) => scanners[i](lastEvaluatedKeys[i])),
특정 segment가 먼저 끝나더라도 요청이 1~2회 정도 차이날거라서 따로 로직을 처리해줘야하나는 조금 고민이네요

2020-07-15 08:21 UTC, breath103 approved these changes

2026-03-31 09:59 UTC, closed without merging